backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/assests/images"
public_folder: "/assests/images"

collections:
  - label: "Site Data"
    name: "site data"
    files:
      - label: "Projects"
        name: "projects"
        file: "public/admin/data/portfolio.json"
        fields:
          - name: projects
            label: projects
            label_singular: Image
            widget: list
            collapsed: true
            fields:
              - { label: "Project name", name: "projectName", widget: "text" }
              - {
                  label: "Project description",
                  name: "projectDescription",
                  widget: "text",
                }
              - {
                  label: "What Did I Learn",
                  name: "whatDidILearn",
                  widget: list,
                  feild: { label: "Item", name: "item", widget: "text" },
                }
              - {
                  label: "Project Images",
                  name: "projectImage",
                  widget: list,
                  field: { label: "Image", name: "image", widget: "image" },
                }
