backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/assests/images"
public_folder: "/assests/images"

collections:
  - label: "Site Data"
    name: "site data"
    files:
      - label: "Projects"
        name: "projects"
        file: "public/admin/data/portfolio.json"
        fields:
          - name: projects
            label: projects
            label_singular: project
            widget: list
            collapsed: true
            fields:
              - { label: "Project name", name: "projectName", widget: "string" }
              - {
                  label: "Project description",
                  name: "projectDescription",
                  widget: "string",
                }
              - {
                  label: "Project Github link",
                  name: "github",
                  widget: "string",
                }
              - { label: "Project Live link", name: "live", widget: "string" }
              - {
                  label: "Technologies used",
                  name: "technologies",
                  widget: list,
                  field:
                    {
                      label: "Technology Name",
                      name: "technology",
                      widget: "string",
                    },
                }
              - {
                  label: "What Did I Learn",
                  name: "whatDidILearn",
                  widget: list,
                  field: { label: "List Item", name: "item", widget: "string" },
                }
              - {
                  label: "Project Images",
                  name: "projectImage",
                  widget: list,
                  field: { label: "Image", name: "image", widget: "image" },
                }
              - {
                  label: "Project Full Details",
                  name: "body",
                  widget: "markdown",
                }
